#!/usr/bin/env bash
set -euo pipefail

# Example: deb-build.sh default git ncdu lsd curl wget duf

sanitize_name() {
  local raw="$1"
  local cleaned
  cleaned="$(printf '%s' "$raw" | tr '[:upper:]' '[:lower:]' | sed -E 's/[^a-z0-9.+-]+/-/g; s/^-+//; s/-+$//')"
  if [[ -z "$cleaned" ]]; then
    echo "invalid"
  else
    echo "$cleaned"
  fi
}

cleanup() {
  if [[ -n "${BUILD_ROOT:-}" && -d "${BUILD_ROOT}" ]]; then
    rm -rf "${BUILD_ROOT}"
  fi
}

# -----------------------------
# Argument parsing
# -----------------------------
OUTPUT_DIR="${OUTPUT_DIR:-/work/out}"
NAME=""
PACKAGES=()

parse_args() {
  if (($# < 2)); then
    echo "error: expected <name> <pkg1> [pkg2 ...]" >&2
    exit 1
  fi

  NAME="$1"
  shift
  PACKAGES=("$@")

  for arg in "${PACKAGES[@]}"; do
    if [[ "$arg" == --* ]]; then
      echo "error: options are not supported in deb-build.sh" >&2
      exit 1
    fi
  done

  if ((${#PACKAGES[@]} == 0)); then
    echo "error: no packages provided" >&2
    exit 1
  fi

  NAME="$(sanitize_name "$NAME")"
  if [[ "$NAME" == "invalid" ]]; then
    echo "error: invalid name" >&2
    exit 1
  fi

  mkdir -p "$OUTPUT_DIR"
}

# -----------------------------
# Package validation
# -----------------------------
validate_packages() {
  local missing=()

  command -v apt-cache >/dev/null 2>&1 || {
    echo "error: required command not found: apt-cache" >&2
    exit 3
  }

  # Refresh indexes when possible, but do not require root for local builds.
  if command -v apt-get >/dev/null 2>&1; then
    if ((EUID == 0)); then
      export DEBIAN_FRONTEND=noninteractive
      apt-get update -qq || true
    fi
  fi

  for pkg in "${PACKAGES[@]}"; do
    if ! apt-cache show "$pkg" >/dev/null 2>&1; then
      missing+=("$pkg")
    fi
  done

  if ((${#missing[@]} > 0)); then
    echo "error: package(s) not found: ${missing[*]}" >&2
    exit 2
  fi
}

# -----------------------------
# Debian package build
# -----------------------------
build_virtual_package() {
  local deps_csv
  local deps_json
  local hash_input
  local hash6
  local package_name
  local pkg_root
  local out_file
  local i

  deps_csv="$(IFS=','; echo "${PACKAGES[*]}")"
  deps_json="["
  for ((i = 0; i < ${#PACKAGES[@]}; i++)); do
    if ((i > 0)); then
      deps_json+=","
    fi
    deps_json+="\"${PACKAGES[$i]}\""
  done
  deps_json+="]"

  hash_input="${PACKAGES[*]}"
  hash6="$(printf '%s' "$hash_input" | sha256sum | cut -c1-6)"
  package_name="${NAME}-${hash6}-virtual"

  BUILD_ROOT="$(mktemp -d /tmp/virtualinstall-build-XXXXXX)"
  pkg_root="${BUILD_ROOT}/${package_name}"
  mkdir -p "${pkg_root}/DEBIAN"

  cat > "${pkg_root}/DEBIAN/control" <<EOF
Package: ${package_name}
Version: 1.0.0
Section: misc
Priority: optional
Architecture: all
Depends: ${deps_csv}
Maintainer: virtualinstall <noreply@example.local>
Description: Virtual dependency package for name '${NAME}'
EOF

  mkdir -p "${pkg_root}/usr/share/doc/${package_name}"
  cat > "${pkg_root}/usr/share/doc/${package_name}/README" <<EOF
This is a virtual package generated by virtualinstall.
It is intended to pull dependency packages for name '${NAME}'.
EOF

  mkdir -p "${pkg_root}/var/lib/virtualinstall/tags"
  cat > "${pkg_root}/var/lib/virtualinstall/tags/${package_name}.json" <<EOF
{
  "name": "${NAME}",
  "virtualPackage": "${package_name}",
  "dependencies": ${deps_json}
}
EOF

  out_file="${OUTPUT_DIR}/${package_name}.deb"
  dpkg-deb --build --root-owner-group "$pkg_root" "$out_file" >/dev/null

  echo "$out_file"
}

# -----------------------------
# Main
# -----------------------------
trap cleanup EXIT

parse_args "$@"
validate_packages
build_virtual_package
